name: Playwright Email Tests - Talent Ticker
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'
    
  workflow_dispatch:
 
defaults:
  run:
    working-directory: playwright
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Create env file
      run: |
        touch .env
        echo 'LOGIN_USERNAME="${{ secrets.PLAYWRIGHT_USERNAME }}"' >> .env
        echo 'LOGIN_PASSWORD="${{ secrets.PLAYWRIGHT_PASSWORD }}"' >> .env 
        echo 'GMAIL_USERNAME="${{ secrets.PLAYWRIGHT_GMAIL_USERNAME }}"' >> .env
        echo 'GMAIL_PASSWORD="${{ secrets.PLAYWRIGHT_GMAIL_PASSWORD }}"' >> .env
        echo 'TEST_EMAIL="${{ secrets.TEST_EMAIL }}"' >> .env
        echo 'MAILOSAUR_SERVER="${{ secrets.MAILOSAUR_SERVER }}"' >> .env
        echo 'MAILOSAUR_API_KEY="${{ secrets.MAILOSAUR_API_KEY }}"' >> .env
        echo 'MAILOSAUR_DOMAIN="${{ secrets.MAILOSAUR_DOMAIN }}"' >> .env
        echo 'MAILOSAUR_PASSWORD="${{ secrets.MAILOSAUR_PASSWORD }}"' >> .env
        echo 'EMAIL_USERNAME="${{ secrets.EMAIL_USERNAME }}"' >> .env
        echo 'EMAIL_PASSWORD="${{ secrets.EMAIL_USERNAME }}"' >> .env
        cat .env
    - name: Run Playwright tests
      run: npx playwright test tests/talent_ticker/email_regression/ --workers=1
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright/playwright-report/
        retention-days: 30
