name: Postman Test Run
on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '12.x'
    
    - name: Install newman
      run: |
       npm install -g newman
       npm install -g newman-reporter-htmlextra
    - name: Make Directory for results
      run: mkdir -p testResults

    - name: Replace email
      run: sed -i.bak -e 's/replaceUsername/${{ secrets.POSTMAN_USERNAME }}/g' './postman/Staging Test.postman_environment.json'
      
    - name: Replace password
      run: sed -i.bak -e 's/replacePassword/${{ secrets.POSTMAN_PASSWORD }}/g' './postman/Staging Test.postman_environment.json'

    - name: Replace secret
      run: sed -i.bak -e 's/replaceSecret/${{ secrets.POSTMAN_AUTH0_SECRET }}/g' './postman/Staging Test.postman_environment.json'

    - name: Replace client
      run: sed -i.bak -e 's/replaceClient/${{ secrets.POSTMAN_AUTH0_CLIENT }}/g' './postman/Staging Test.postman_environment.json'

    - name: View the env file
      run: cat './postman/Staging Test.postman_environment.json'

    - name: Run POSTMAN collection
      run: trap $(newman run "./postman/Automation Tests.postman_collection.json" -e "./postman/Staging Test.postman_environment.json" -r htmlextra --reporter-htmlextra-export testResults/ttreport1.html --reporter-htmlextra-darkTheme > testResults/runreport1.html) 1
      
      # Upload the contents of Test Results directory to workspace
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
       name: RunReports
       path: testResults
