name: Playwright - Regression Tests - Stage Only
on:
  pull_request_target:
    types:
      - opened

jobs:
  stage-regression-tests-workflow:
    uses: TalentTicker/regression-tests/.github/workflows/staging.yml@tt5-2047/trigger-staging
